---
layout: page
title: "데이터 사이언스 - 파이썬"
subtitle: "파이썬 comprehension"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(reticulate)
use_condaenv("anaconda3")
# reticulate::repl_python()
```


# 파이썬 `comprehension` [^iterable-iterator] [^python-comprehension] {#python-comprehension}

[^iterable-iterator]: [이터레이터와 제너레이터, "Iterables vs. Iterators vs. Generators" 번역](https://mingrammer.com/translation-iterators-vs-generators/)

[^python-comprehension]: [파이썬의 Comprehension 소개](https://mingrammer.com/introduce-comprehension-of-python/)

파이썬 `comprehension`은 반복가능한 객체(iterable object)를 생성하는 방법으로 이를 통해서 리스트, 집합(set), 딕셔너리, 생성자(generator)를 생성시킬 수 있다. `Comprehension`이란 반복가능한(iterable)한 객체를 생성시키는 파이썬에서 자주 사용하는 방법으로 자료형에 따라 다음과 같이 나눠진다.

- List Comprehension: 리스트
- Set Comprehension: 집합
- Dictionary Comprehension: 딕셔너리
- Generator Expression: 생성자

# 리스트 `comprehensions` [^list-comprehension] {#python-list-comprehension}

[^list-comprehension]: [mingrammer's note, '파이썬의 Comprehension 소개'](https://mingrammer.com/introduce-comprehension-of-python/)

`List comprehensions`에 대한 적절한 번역은 없는 상황이라 '리스트 축약' 혹은 '리스트 포함'이라고 번역하는 경우가 가끔있고 그냥 영어로 `List comprehensions`을 사용한다. 

## 들어가며  {#python-list-comprehension}

리스트로 숫자가 담긴 객체 `numbers`가 있다 모든 숫자에 2를 곱하고자 하는 경우
다음과 같이 2를 곱한 연산 결과를 담을 리스트 객체 `res_number`를 만들어 생성시킨다.
그리고 나서 리스트 각 원소를 꺼내 2를 곱한 후에 `.append()` 메쏘드로 각 계산된 값을 채워넣는다.

```{python python-list-comprehension}
numbers = [1,2,3,4,5]

res_number = []

for number in numbers:
    res_number.append(number * 2)

print(res_number)
```

`for`문장으로 작성한 코드가 `list comprehension`으로 작성하게 되면 2줄이 한 줄로 준 것을 확인할 수 있다.

```{python python-list-comprehension-do-it}
lc_number = [number * 2 for number in numbers]

print(lc_number)
```

`list comprehension`은 표현식, 반복변수, 반복자로 구성되어 `for` 루프를 한줄로 간결하게 표현할 수 있도록 도움을 준다.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">

- **list comprehension 구성요소 **
    - 표현식: `number * 2`
    - 반복변수(iterator variable): `number`
    - 반복자(iterator): 리스트 `numbers`

</div>

## 조건문이 붙은 `list comprehension` {#python-list-comprehension-conditional}

먼저 `list comprehension`을 사용해서 1--10사이 숫자를 리스트에 담아둔다.
조건문(`conditional`)을 `list comprehension` 뒤에 붙여 1 -- 10까지 숫자 중 짝수와 홀수만 발라낸다.
`%`는 나머지 연산자를 사용해서 2로 나눠 0과 1을 기준으로 홀수와 짝수로 구분한다.

- 짝수: 12345678910 &rarr; 246810
- 홀수: 12345678910 &rarr; 13579

```{python python-list-comprehension-conditional}
whole_numbers = [number for number in range(1, 11)]
print(f"전체 숫자: {whole_numbers}")

even_numbers = [number for number in whole_numbers if number % 2 == 0]
print(f"짝수: {even_numbers}")

odd_numbers = [number for number in whole_numbers if number % 2 == 1]
print(f"홀수: {odd_numbers}")
```

`if` 조건문을 앞으로 가져와서 `if-else`조합을 하게 되면 짝수만 남겨두고 홀수를 0으로 대체하는 것이 가능하다.

```{python python-list-comprehension-conditional2}
only_even_numbers = [number if number % 2 == 0 else 0 for number in whole_numbers]
print(f"짝수: {only_even_numbers}")
```

## 다중 `for` 루프 {#python-list-comprehension-multiple-loop}

튜플 리스트를 생성하는데 `for` 루프를 사용하는 것과 리스트 comprehension을 사용하는 경우를 비교하여 보자.

<div class = "row">
  <div class = "col-md-6">
**다중 `for`루프**

먼저 문자와 숫자를 조합하여 튜플을 만들고 이를 이중 `for` 루프를 사용해서 튜플 리스트로 작성한다. 

```{python python-list-comprehension-loop}
letters = ['X', 'Y', 'Z']
numbers = [1, 2, 3]

results = []

for letter in letters:
    for number in numbers:
        results.append((letter, number))

print(results)        
```


  </div>
  <div class = "col-md-6">
**리스트 comprehension**

튜플 리스트를 이중 `for` 루프를 사용하는 것과 비교하여 한줄로 단순화 시킬 수 있다.

```{python python-list-comprehension-run}
[(letter, number) for letter in letters for number in numbers]
```

  </div>
</div>


# 단어 주머니(bag of words) 사례 {#list-comprehension-bow} 

위키백과사전 [Bag-of-words model](https://en.wikipedia.org/wiki/Bag-of-words_model)에 포함된 단어주머니 모형을 리스트 comprehension을 사용해서 구현해본다.

1. 문자열로 구성된 문장이 하나 있다고 가정한다. `bow_text`
1. `string` 팩키지 `string.punctuation`와 조건을 갖는 comprehension을 사용해서 구두점을 제거한다.
1. 메쏘드 체인을 활용하여 소문자 변환 후 공백 기준으로 단어를 쪼갠다. 연산작업 결과 리스트가 반환됨.
1. 중복 단어가 없어야 되서 `set()` 함수로 집합을 생성시키고 이를 튜플의 키로 사용한다.
1. 리스트 comprehension을 사용해서 단어 갯수를 센다.
1. `sorted()` 함수를 사용해서 `key=`를 값으로 지정하고 역순으로 정렬하여 출력시킨다.

```{python bag-of-words-list-comprehension}
import string

# 예제 문장
bow_text = 'John likes to watch movies. Mary likes movies too. John also likes to watch football games.'

# 소문자 변환 후 단어 쪼개기
bow_text_stripped = ''.join(c for c in bow_text if not c in string.punctuation) # 구두점 제거
bow_list = bow_text_stripped.lower().split()

# 단어 집합
bow_set = set(bow_list)

# 단어 갯수 세기
bow_tup_list = [ (word, bow_list.count(word)) for word in bow_set ]

# 리스트 튜플 정렬
sorted(bow_tup_list, key = lambda x: x[1], reverse=True)

```

# 최대공약수 사례 [^stackoverflow-gcd] {#list-comprehension-gcd} 

[^stackoverflow-gcd]: [stackoverflow, "Code for Greatest Common Divisor in Python"](https://stackoverflow.com/questions/11175131/code-for-greatest-common-divisor-in-python)

난수를 0-10 사이 난수를 5개씩 추출하는데 중복을 방지하고자 `set()` 함수를 사용한다. 그리고 `fractions` 라이브러리 `gcd()` 함수를 사용해서 두 리스트 사이 최대공약수를 뽑아낸다.

```{python gcd-list-comprehension}
# 두 리스트에서 최대공약수 찾아내기
import random
from random import randint 
random.seed(777)

list_one = list(set([randint(0,10) for i in range(5)]))
list_two = list(set([randint(0,10) for j in range(5)]))

print("첫번째 리스트:", list_one, "\n두번째 리스트", list_two)

## 최대공약수 
from fractions import gcd

[(i,j) for i in list_one
       for j in list_two if gcd(i,j) == 1] 
```

다른 방법은 최대공약수를 재귀(recursion)를 사용하는 것이다.

```{python gcd-list-comprehension-recursion}
def gcd_recur (x, y):
    if y == 0:
        return x
    else:
        return gcd_recur(y, x % y)

[(i,j) for i in list_one
       for j in list_two if gcd_recur(i,j) == 1] 
```


# 딕셔너리 `comprehension` {#python-dictionary-comprehension}

`dictinary comprehension`은 동일하고 `[` 대신에 `{`을 사용한다는 측면에서 차이가 난다.
짝수면 2로 나누고 홀수면 -1을 곱하여 음수로 만든 딕셔너리를 만들어낸다.

```{python python-dictionary-comprehension}
dict_numbers = {number / 2 if number % 2 == 0 else -number for number in whole_numbers}
print(f"딕셔너리 매직: {dict_numbers}")
```

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">

`리스트(list)`와  `딕셔너리(Dictionary)`를 다음표를 통해서 비교할 수 있다.

| 리스트(list) | 딕셔너리(Dictionary) |
|--------------------------|--------------------------|
| `[]`을 사용해서 선택, 갱신, 제거 | `[]`을 사용해서 선택, 갱신, 제거 |
| 숫자 범위를 `index`로 사용 | 유일무이한 키를 `index`로 사용 |
| 값(value)들을 모아놓은 것, 순서가 있음 | 유일무이한 키를 갖는 lookup 테이블 |

</div>


